"""mkdocs hooks: mirrored-content path rewrites, and the Benchmarks nav.

Two jobs:

* Upstream files reference repo-relative paths (`../../tileops/...`,
  `../../.claude/skills/<name>/SKILL.md`, `../../docs/design/...`) that
  don't resolve once mirrored into this site. We rewrite them at the
  `on_page_markdown` stage, after the include-markdown plugin has pulled
  content in.
* The Benchmarks section is generated by `scripts/gen_bench_pages.py` at
  deploy time, so its pages cannot be listed in `mkdocs.yml`. `on_config`
  expands that one nav entry to whichever pages the renderer produced.
"""
from __future__ import annotations

import os
import re

UPSTREAM_BLOB = "https://github.com/tile-ai/TileOPs/blob/main"

_SKILL_LINK = re.compile(r"(?:\.\./)+\.claude/skills/([\w-]+)/SKILL\.md")
_SKILL_DESIGN_REF = re.compile(r"\.\./\.\./\.\./docs/design/")
_SKILL_SIBLING = re.compile(r"\.\./([\w-]+)/SKILL\.md")
_DESIGN_REPO_PATH = re.compile(r"\.\./\.\./([\w./-]+)")


def on_page_markdown(markdown, page, config, files):
    src = page.file.src_path.replace("\\", "/")

    if src.startswith("design/"):
        # Upstream design docs link to source files via ../../<repo path>.
        # Redirect those to GitHub so they resolve from the published site.
        markdown = _DESIGN_REPO_PATH.sub(rf"{UPSTREAM_BLOB}/\1", markdown)

    elif src.startswith("skills/"):
        # Catalog and overview embed sections that link to .claude/skills/<name>/SKILL.md
        # — redirect to the local guide page.
        markdown = _SKILL_LINK.sub(r"\1.md", markdown)
        # Per-skill guide pages embed SKILL.md, which links to design docs via
        # ../../../docs/design/ and to sibling skills via ../<name>/SKILL.md.
        markdown = _SKILL_DESIGN_REF.sub("../design/", markdown)
        markdown = _SKILL_SIBLING.sub(r"\1.md", markdown)

    return markdown


# Benchmarks pages in nav order. A page the renderer did not produce is left
# out; a page it produced that is not listed here is appended, so a new data
# page reaches the nav without editing this list.
_BENCH_ORDER = [
    "index.md", "reading.md", "attention.md", "linear-attention.md",
    "gemm-moe.md", "elementwise-reduction.md", "norm-conv-pool.md",
]


def on_config(config):
    """Expand the Benchmarks nav entry to the generated pages."""
    bench_dir = os.path.join(config["docs_dir"], "benchmarks")
    if not os.path.isdir(bench_dir):
        return config
    present = {f for f in os.listdir(bench_dir) if f.endswith(".md")}
    ordered = [f for f in _BENCH_ORDER if f in present]
    ordered += sorted(present - set(ordered))
    entries = [f"benchmarks/{f}" for f in ordered]

    for section in config["nav"]:
        if isinstance(section, dict) and "Benchmarks" in section:
            section["Benchmarks"] = entries
    return config
